version: 2
updates:
- package-ecosystem: nuget
  directories:
    - "/sample/SampleLambda-dotnet6"
    - "/sample/SampleLambda-dotnet7"
    - "/sample/SampleLambda-dotnet8"
  schedule:
    interval: daily
    time: "04:00"
  rebase-strategy: disabled
  ignore:
    - dependency-name: "HeadlessChromium.Puppeteer.Lambda.Dotnet"
- package-ecosystem: nuget
  directory: "/src/HeadlessChromium.Puppeteer.Lambda.Dotnet"
  schedule:
    interval: daily
    time: "04:00"
  rebase-strategy: disabled
  ignore:
    - dependency-name: "PuppeteerSharp"
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  rebase-strategy: disabled
